// ==========================================
// コマンドテンプレート定義
// よく使うSui/Walrusコマンドをテンプレ化
// ==========================================
import type { CommandTemplate } from '../types';

export const SUI_TEMPLATES: CommandTemplate[] = [
  // --- 情報系 (Low Risk, Read Only) ---
  {
    id: 'sui-addresses',
    name: 'ウォレット一覧',
    description: '登録済みのウォレットアドレスを一覧表示',
    cli_type: 'sui',
    category: '情報',
    command: 'client addresses',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'sui-active-address',
    name: 'アクティブアドレス',
    description: '現在選択中のウォレットアドレスを表示',
    cli_type: 'sui',
    category: '情報',
    command: 'client active-address',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'sui-balance',
    name: '残高確認',
    description: 'ウォレットの残高を確認',
    cli_type: 'sui',
    category: '情報',
    command: 'client balance',
    args: [
      {
        name: 'address',
        description: '対象アドレス（空欄でアクティブアドレス）',
        required: false,
        type: 'address',
        advanced: true,
      },
    ],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'sui-gas',
    name: 'ガスコイン一覧',
    description: 'ガスコインの一覧を表示',
    cli_type: 'sui',
    category: '情報',
    command: 'client gas',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'sui-envs',
    name: '環境一覧',
    description: '設定済みのネットワーク環境を一覧表示',
    cli_type: 'sui',
    category: '情報',
    command: 'client envs',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'sui-active-env',
    name: 'アクティブ環境',
    description: '現在選択中のネットワーク環境を表示',
    cli_type: 'sui',
    category: '情報',
    command: 'client active-env',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'sui-objects',
    name: 'オブジェクト一覧',
    description: '所有オブジェクトの一覧を表示',
    cli_type: 'sui',
    category: '情報',
    command: 'client objects',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },

  // --- 操作系 ---
  {
    id: 'sui-switch-address',
    name: 'ウォレット切替',
    description: 'アクティブウォレットを切り替え',
    cli_type: 'sui',
    category: '操作',
    command: 'client switch --address',
    args: [
      {
        name: 'address',
        description: '切替先アドレスまたはエイリアス',
        required: true,
        type: 'string',
      },
    ],
    risk_level: 'medium',
    is_read_only: false,
  },
  {
    id: 'sui-switch-env',
    name: '環境切替',
    description: 'アクティブネットワーク環境を切り替え',
    cli_type: 'sui',
    category: '操作',
    command: 'client switch --env',
    args: [
      {
        name: 'env',
        description: '環境名（mainnet, testnet, devnet 等）',
        required: true,
        type: 'select',
        options: ['mainnet', 'testnet', 'devnet'],
      },
    ],
    risk_level: 'medium',
    is_read_only: false,
  },
  {
    id: 'sui-faucet',
    name: 'テストSUI取得',
    description: 'テストネットのSUIを取得（テストネット専用）',
    cli_type: 'sui',
    category: '操作',
    command: 'client faucet',
    args: [],
    risk_level: 'low',
    is_read_only: false,
  },

  // --- 高リスク操作 ---
  {
    id: 'sui-transfer',
    name: 'SUI送金',
    description: 'SUIトークンを送金',
    cli_type: 'sui',
    category: '送金',
    command: 'client transfer-sui',
    args: [
      {
        name: 'to',
        description: '送金先アドレス',
        required: true,
        type: 'address',
      },
      {
        name: 'sui-coin-object-id',
        description: '送金元のコインオブジェクトID',
        required: true,
        type: 'string',
      },
      {
        name: 'amount',
        description: '送金額（MIST単位）',
        required: false,
        type: 'number',
        advanced: true,
      },
      {
        name: 'gas-budget',
        description: 'ガスバジェット',
        required: true,
        type: 'number',
        default_value: '50000000',
      },
    ],
    risk_level: 'high',
    is_read_only: false,
  },
];

export const WALRUS_TEMPLATES: CommandTemplate[] = [
  // --- 情報系 ---
  {
    id: 'walrus-info',
    name: 'システム情報',
    description: 'Walrusストレージシステムの情報を表示',
    cli_type: 'walrus',
    category: '情報',
    command: 'info',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'walrus-list-blobs',
    name: 'Blob一覧',
    description: '登録済みのBlobを一覧表示',
    cli_type: 'walrus',
    category: '情報',
    command: 'list-blobs',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'walrus-blob-status',
    name: 'Blobステータス',
    description: '指定Blobのステータスを確認',
    cli_type: 'walrus',
    category: '情報',
    command: 'blob-status',
    args: [
      {
        name: 'blob-id',
        description: 'Blob ID',
        required: true,
        type: 'string',
        arg_style: 'positional',
      },
    ],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'walrus-health',
    name: 'ヘルス確認',
    description: 'ストレージノードのヘルス状態を確認',
    cli_type: 'walrus',
    category: '情報',
    command: 'health',
    args: [],
    risk_level: 'low',
    is_read_only: true,
  },
  {
    id: 'walrus-blob-id',
    name: 'Blob IDエンコード',
    description: 'ファイルからBlob IDを計算',
    cli_type: 'walrus',
    category: '情報',
    command: 'blob-id',
    args: [
      {
        name: 'file',
        description: 'ファイルパス',
        required: true,
        type: 'string',
        is_path: true,
        path_type: 'file',
        arg_style: 'positional',
      },
    ],
    risk_level: 'low',
    is_read_only: true,
  },

  // --- 操作系 ---
  {
    id: 'walrus-store',
    name: 'データ保存',
    description: 'Walrusにデータを保存',
    cli_type: 'walrus',
    category: '操作',
    command: 'store',
    args: [
      {
        name: 'file',
        description: '保存するファイルパス',
        required: true,
        type: 'string',
        is_path: true,
        path_type: 'file',
        arg_style: 'positional',
      },
      {
        name: 'epochs',
        description: '保存期間（エポック数）',
        required: false,
        type: 'number',
        advanced: true,
        arg_style: 'flag',
        flag_name: '--epochs',
      },
    ],
    risk_level: 'medium',
    is_read_only: false,
  },
  {
    id: 'walrus-read',
    name: 'データ読み取り',
    description: 'WalrusからBlobを読み取り',
    cli_type: 'walrus',
    category: '操作',
    command: 'read',
    args: [
      {
        name: 'blob-id',
        description: 'Blob ID',
        required: true,
        type: 'string',
        arg_style: 'positional',
      },
      {
        name: 'out',
        description: '出力先ファイルパス',
        required: false,
        type: 'string',
        advanced: true,
        is_path: true,
        path_type: 'file',
        arg_style: 'positional',
      },
    ],
    risk_level: 'low',
    is_read_only: true,
  },

  // --- 高リスク ---
  {
    id: 'walrus-delete',
    name: 'Blob削除',
    description: 'WalrusからBlobを削除',
    cli_type: 'walrus',
    category: '削除',
    command: 'delete',
    args: [
      {
        name: 'blob-id',
        description: '削除するBlob ID',
        required: true,
        type: 'string',
        arg_style: 'positional',
      },
    ],
    risk_level: 'high',
    is_read_only: false,
  },
  {
    id: 'walrus-burn-blobs',
    name: 'Blob焼却',
    description: 'BlobオブジェクトをSui上で焼却',
    cli_type: 'walrus',
    category: '削除',
    command: 'burn-blobs',
    args: [
      {
        name: 'blob-object-ids',
        description: 'Blobオブジェクト ID（カンマ区切り可）',
        required: true,
        type: 'string',
        arg_style: 'positional',
      },
    ],
    risk_level: 'high',
    is_read_only: false,
  },
];

export const SITE_BUILDER_TEMPLATES: CommandTemplate[] = [
  {
    id: 'site-builder-deploy',
    name: '一括デプロイ (推奨)',
    description: 'site-config.yaml に基づいてサイトをデプロイ。Windows環境ではこちらが最も安定しています。',
    cli_type: 'site-builder',
    category: 'サイト',
    command: 'deploy',
    args: [],
    risk_level: 'medium',
    is_read_only: false,
  },
  {
    id: 'site-builder-publish',
    name: 'サイト新規公開',
    description: 'フォルダを Walrus Site として新規に公開',
    cli_type: 'site-builder',
    category: 'サイト',
    command: 'publish',
    args: [
      {
        name: 'epochs',
        description: '保存期間(エポック数)',
        required: false,
        type: 'number',
        arg_style: 'flag',
        flag_name: '--epochs',
      },
      {
        name: 'earliest-expiry-time',
        description: '最短有効期限 (日時)',
        required: false,
        type: 'string',
        arg_style: 'flag',
        flag_name: '--earliest-expiry-time',
        advanced: true,
      },
      {
        name: 'end-epoch',
        description: '終了エポック番号',
        required: false,
        type: 'number',
        arg_style: 'flag',
        flag_name: '--end-epoch',
        advanced: true,
      },
      {
        name: 'path',
        description: '公開するフォルダのパス',
        required: true,
        type: 'string',
        is_path: true,
        path_type: 'directory',
        arg_style: 'positional',
      },
    ],
    risk_level: 'medium',
    is_read_only: false,
  },
  {
    id: 'site-builder-update',
    name: 'サイト更新 (※不安定)',
    description: '既存の Walrus Site を更新。Windowsの一部環境でクラッシュする場合は「一括デプロイ」を使用してください。',
    cli_type: 'site-builder',
    category: 'サイト',
    command: 'update --list-directory',
    args: [
      {
        name: 'epochs',
        description: '延長期間(エポック数)',
        required: false,
        type: 'number',
        arg_style: 'flag',
        flag_name: '--epochs',
      },
      {
        name: 'earliest-expiry-time',
        description: '最短有効期限 (日時)',
        required: false,
        type: 'string',
        arg_style: 'flag',
        flag_name: '--earliest-expiry-time',
        advanced: true,
      },
      {
        name: 'end-epoch',
        description: '終了エポック番号',
        required: false,
        type: 'number',
        arg_style: 'flag',
        flag_name: '--end-epoch',
        advanced: true,
      },
      {
        name: 'path',
        description: '更新するフォルダのパス',
        required: true,
        type: 'string',
        is_path: true,
        path_type: 'directory',
        arg_style: 'positional',
      },
      {
        name: 'site-id',
        description: '更新対象の Site オブジェクト ID',
        required: true,
        type: 'address',
        arg_style: 'positional',
      },
    ],
    risk_level: 'medium',
    is_read_only: false,
  },
];

export const ALL_TEMPLATES = [...SUI_TEMPLATES, ...WALRUS_TEMPLATES, ...SITE_BUILDER_TEMPLATES];
